wireapp/wire-web-ets

- Jenkinsfile
- README.md
- package.json
- src/main/InstanceService.ts
- src/main/index.ts
- src/main/routes/instance/assetRoutes.ts
- src/main/routes/instance/conversationRoutes.ts
- src/main/routes/instance/typingRoutes.ts
This PR reverts #8 and implements all changes for the finished API v1.
> refactor: API v1 finishing

- README.md
- package.json
- src/main/InstanceService.ts
- src/main/routes/instance/conversationRoutes.ts
- yarn.lock
> feat: Delete Messages

- src/main/InstanceService.ts
- src/main/routes/instance/assetRoutes.ts
- src/main/utils.ts
If the service gets killed it will log
```
[2018-07-18 10:39:10] Received SIGINT signal. Exiting.
```
> feat: Extended logging

- README.md
- src/main/InstanceService.ts
- src/main/routes/instance/conversationRoutes.ts
Merge after https://github.com/wireapp/wire-web-ets/pull/140.
> feat: Send reaction

- src/main/InstanceService.ts
I removed the image data to keep the stored messages small.
> fix: Also add image messages to stored messages

- src/main/InstanceService.ts
Mergeable after https://github.com/wireapp/wire-web-packages/pull/944 and new `core` release.
> feat: Replace incoming edited messages (WEBFOUND-19)

- src/main/InstanceService.ts
With this PR we will have the `uploaded` and `preview` fields in assets merged together.
> feat: Merge assets in message collection (WEBFOUND-20)

- README.md
I created tickets for all planned endpoints here: 
- https://wearezeta.atlassian.net/secure/RapidBoard.jspa?rapidView=58&projectKey=WEBFOUND
> chore: Replace planned items with Jira tickets

- README.md
- src/main/InstanceService.ts
- src/main/routes/instance/assetRoutes.ts
Only mergeable after https://github.com/wireapp/wire-web-packages/pull/1022 and a new `core` release.
> feat: Send link previews (WEBFOUND-27)

- README.md
- src/main/InstanceService.ts
- src/main/routes/instance/assetRoutes.ts
- src/main/routes/instance/conversationRoutes.ts
Mergeable after https://github.com/wireapp/wire-web-packages/pull/1029 and a new `core` release.
> feat: Edit link preview

- Jenkinsfile
- README.md
- ecosystem.config.js
- package.json
- spec/test/RoutesSpec.js
- src/main/InstanceService.ts
- src/main/index.ts
- src/main/routes/error/errorRoutes.ts
- src/main/routes/instance/assetRoutes.ts
- src/main/routes/instance/conversationRoutes.ts
- src/main/routes/log/logRoute.ts
- src/main/routes/mainRoute.ts
- src/main/utils.ts
- yarn.lock
* Fix for crash WEBFOUND-36
* Logrotation with pm2
* Dependency updates
> Merge "dev" to "master"

- README.md
- spec/test/RoutesSpec.js
- src/main/InstanceService.ts
- src/main/middlewares/joiValidate.ts
- src/main/routes/instance/assetRoutes.ts
- src/main/routes/instance/conversationRoutes.ts
Blocked by https://github.com/wireapp/wire-web-packages/pull/1098 and a new `core` release.
> feat: Mentions

- src/main/InstanceService.ts
Blocked by https://github.com/wireapp/wire-web-packages/pull/1125 and a new `core` release.
> feat: Add listeners for deletion and location (WEBFOUND-44, WEBFOUND-45)

- Jenkinsfile
- README.md
- src/Server.ts
- src/routes/commit/commitRoute.ts
- src/routes/mainRoute.ts
* **New route**: `/commit`, which returns the latest commit hash.
* **Added**: The route `/` now also includes the latest commit.
> feat: Add commit route

- README.md
- docs/swagger.md
- src/InstanceService.ts
- src/routes/instance/mainRoutes.ts
- swagger.json
Creating legal hold clients via `/clients` is not possible anymore.
> feat: Remove custom device class

- README.md
- package.json
- src/InstanceService.ts
- src/routes/instance/conversationRoutes.ts
- swagger.json
- yarn.lock
- http://localhost:21080/swagger-ui/#/Instance/sendButtonAction
> feat: Send button actions

- src/instance/InstanceController.ts
- src/instance/InstanceFileOptions.ts
- src/instance/InstanceService.ts
Produces this:
But we need this:
> feat: Add /sendFile endpoint

- package.json
- src/instance/InstanceController.ts
- yarn.lock
Reverts wireapp/wire-web-ets#1374
> Revert "chore(deps): bump class-validator from 0.11.1 to 0.12.2"

- package.json
- yarn.lock
Reverts wireapp/wire-web-ets#2141
> Revert "chore(deps): Bump @wireapp/core from 17.13.0 to 17.21.1"

- src/instance/InstanceArchiveOptions.ts
- src/instance/InstanceButtonOptions.ts
- src/instance/InstanceDeleteOptions.ts
- src/instance/InstanceDeliveryOptions.ts
- src/instance/InstanceFileOptions.ts
- src/instance/InstanceImageOptions.ts
- src/instance/InstanceLocationOptions.ts
> fix: add missing uuid checks

- package.json
- src/instance/InstanceController.ts
- src/instance/InstanceCreationOptions.ts
- src/instance/InstanceService.ts
- yarn.lock
----
- The **PR Title**
- The **PR Description**
----
This enables federation features
> feat: Enable message editing and deleting for federated env

- src/instance/InstanceController.ts
- src/instance/InstanceTextOptions.ts
----
- The **PR Title**
- The **PR Description**
----
_Briefly describe the issue you have solved or implemented with this pull request. If the PR contains multiple issues, use a bullet list._
_Briefly describe the causes behind the issues. This could be helpful to understand the adopted solutions behind some nasty bugs or complex issues._
_Briefly describe the solutions you have implemented for the issues explained above._
_If there are some other pull requests related to this one (e.g. new releases of frameworks), specify them here._
Needs releases with:
_Briefly describe how this change was tested and if applicable the exact steps taken to verify that it works as expected._
_Specify here any other facts that you think are important for this issue._
_Attachments like images, videos, …
> feat: Add userDomain to mentions

- src/send/sendFile.ts
fixed an issue where changing the algorithm and hash for sending files was not being tested correctly.
> fix: solve issue with hash and algo not working

- src/instance/InstanceCallOptions.ts
- src/instance/InstanceController.ts
- src/instance/InstanceService.ts
This PR adds the ability to initiate calls using the ets api
> feat: add api endpoint to support sendCall
